### PR TITLE
Adding QueuePlugin and updating LockPlugin

### PR DESCRIPTION
**Pull request by zackurben**
Adding QueuePlugin for the ability to queue jobs within jobs and refactoring LockPlugin.

### CODE REVIEW

**Comment by zackurben** [comment]
Can one of you can review this when you have a second? @arturo-c @albertvolkman

**Comment by arturo-c** [comment]
@zackurben tried merging yesterday, but not sure why I'm not a maintainer, @albertvolkman will have to do it

**Comment by zackurben** [comment]
@arturo-c ah gotcha, thanks man; hope all is well!

**Comment by albertvolkman** [comment]
I don't have permissions either. There must be some issue with @hubdrop. @jonpugh?

**Comment by zackurben** [comment]
@albertvolkman ah, thanks for pinging the others!

**Comment by arturo-c** [comment]
@zackurben yea, def something screwy with github, I pushed your changes to the 6.x-1.x branch in drupal and added you as a maintainer, I think the hubdrop project is not being maintained so I would just keep everything in drupals git for now.

**Comment by zackurben** [comment]
@arturo-c Thanks for looking into it man, will do.

**Pull request merged**
